name: ml_apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.16

flutter_icons:    
  android: true # should be bool or path to icon
  ios: true    
  image_path: "assets/logo.png" # path icon
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/logo.png
    # branding: assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/
